version: '3.4'

services: 
  app:
    build:
      context: .
      target: release
    image: hummingbird
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_STORAGE_BUCKET_NAME:
      AWS_LOCATION:
      BINO_URL: 'http://localhost:8080/'
    network_mode: host
  
